### ISSUE TITLE
Allow to disable synchronization 

### ISSUE THREAD

**Issue by janluke** [pradyunsg/sphinx-inline-tabs#20] opened 2021-05-12 15:18 UTC
Synchronization may be a good default but it shouldn't be enforced. There's a common scenario for tabs where synchronization is not desirable: the "input / output" scenario. I think it is as common as the "multiple languages" scenario, if not more common.

I'm using sphinx-panels at the moment but it'd be nice to have this feature in this nice extension.

Thanks for your work!

**Comment by pradyunsg** [comment] 2021-05-12 16:10
Closing as a duplicate of #18, since it's the same usecase.

**Closed as completed by pradyunsg** 2021-05-12 16:10 UTC
