### ISSUE TITLE
Clicking and dragging a tab title causes *other* tabs to change but not the clicked tab

### ISSUE THREAD

**Issue by choldgraf** [pradyunsg/sphinx-inline-tabs#5] opened 2020-11-15 01:27 UTC
This seems edge-casey but I think it may be more common than expected. If you click and accidentally drag to highlight a letter or two, then all *other* tabs on the page will change, but the clicked tab will not. I accidentally did this a few times when testing it out, enough that it might be worth mentioning in the docs or edge-casing in the code.

![2020-11-14_17-28-17](https://user-images.githubusercontent.com/1839645/99160711-cf53dc80-269e-11eb-9e7f-dce41d2ca8e3.gif)

**Comment by pradyunsg** [comment] 2021-01-10 13:06
Thanks for testing and filing this issue! ^>^

This definitely needs some JS tweaking, but I'm not _too_ motivated right now, because as you noted, this is a little edge-casey. :)

**Comment by christopherpickering** [comment] 2021-04-30 12:30
@choldgraf what browser does that? I tried in safari and can't reproduce it.

**Comment by choldgraf** [comment] 2021-04-30 22:45
Chrome

**Comment by christopherpickering** [comment] 2021-05-03 13:15
@choldgraf oh yeah, interesting, its the same problem in Firefox. The new box is being checked properly, but looks like those browsers are not unchecking the other radio boxes when the mouse drags. You can reproduce the same issue in w3school's radio box demo https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_radio.

I changed line 18 of the tabs.js from 
```js
if (label === this) continue;
```

to 

```js
if (label === this) label.previousSibling.checked = false;
```
to force uncheck the "unseleceted" boxes all the time, and it seems to fix this issue. I'll put a pr for it.

**Comment by pradyunsg** [comment] 2021-12-22 14:52
Fixed in https://github.com/pradyunsg/sphinx-inline-tabs/commit/6d3d8e771ef87eb49cb54b16fe2ba188c319d6b9. :)

**Closed as completed by pradyunsg** 2021-12-22 14:52 UTC
Labels: bug
